spring.application.name=assistant

spring.datasource.password=secret
spring.datasource.username=root
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase

spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=mistral

spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=mxbai-embed-large

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.vectorstore.pgvector.initialize-schema=true
